# Generated by Django 5.1.3 on 2025-01-14 15:33

import django.core.validators
import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', markdownx.models.MarkdownxField(help_text='Problem description in Markdown format')),
                ('input_format', markdownx.models.MarkdownxField(help_text='Input format specification')),
                ('output_format', markdownx.models.MarkdownxField(help_text='Output format specification')),
                ('constraints', markdownx.models.MarkdownxField(help_text='Problem constraints')),
                ('sample_explanation', markdownx.models.MarkdownxField(help_text='Explanation of sample test cases')),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=1)),
                ('time_limit', models.IntegerField(help_text='Time limit in milliseconds')),
                ('memory_limit', models.IntegerField(help_text='Memory limit in MB')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('acceptance_rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('related_problems', models.ManyToManyField(blank=True, related_name='related_to', to='problems.problem')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField()),
                ('order', models.IntegerField(default=0)),
                ('is_premium', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='problems.problem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_sample', models.BooleanField(default=False)),
                ('explanation', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
