# Generated by Django 5.1.6 on 2025-02-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
