# Generated by Django 5.1.6 on 2025-02-09 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_problem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='problemhint',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_hints_detail', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='problem',
            name='hints',
            field=models.ManyToManyField(blank=True, related_name='problem_hints', to='problems.hint'),
        ),
        migrations.AddField(
            model_name='problem',
            name='topicTags',
            field=models.ManyToManyField(blank=True, related_name='problem_topicTags', to='problems.tag'),
        ),
    ]
