# Generated by Django 5.1.6 on 2025-02-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_hint_tag_alter_problemhint_problem_problem_hints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
