# Generated by Django 5.1.6 on 2025-02-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_alter_problem_hints_alter_problem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
