# Generated by Django 5.1.6 on 2025-02-09 09:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_alter_problem_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hint',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='hints',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='topicTags',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='constraints',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='input_format',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='output_format',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='sample_explanation',
        ),
        migrations.DeleteModel(
            name='ProblemHint',
        ),
        migrations.AddField(
            model_name='problem',
            name='hints',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='problem',
            name='topicTags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
