# Generated by Django 5.1.6 on 2025-02-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_remove_problem_private_testcases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='default_code_templates',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
