# Generated by Django 5.1.6 on 2025-02-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
