# Generated by Django 5.1.6 on 2025-02-07 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_alter_interviewsession_id'),
        ('problems', '0002_alter_problem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewsession',
            name='question',
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.problem'),
        ),
    ]
