# Generated by Django 5.1.6 on 2025-03-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_interviewsession_initial_prompt_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
