# Generated by Django 5.1.5 on 2025-01-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(choices=[('PY', 'Python'), ('CPP', 'C++')], max_length=10)),
                ('status', models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error')], default='CE', max_length=3)),
                ('execution_time', models.IntegerField(null=True)),
                ('memory_used', models.IntegerField(null=True)),
                ('test_cases', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='submissions_status_ffd1ec_idx')],
            },
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
