# Generated by Django 5.1.5 on 2025-01-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_codesubmission_delete_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(choices=[('PY', 'Python'), ('CPP', 'C++')], max_length=20),
        ),
    ]
