# Generated by Django 5.1.5 on 2025-01-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_alter_codesubmission_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(choices=[('PY', 'Python'), ('CPP', 'C++')], max_length=10),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error')], default='CE', max_length=20),
        ),
    ]
